// backend-agent/web/src/views/LoginView.vue
<script setup>
import { reactive, ref } from 'vue'
import { Lock, User } from '@element-plus/icons-vue'

const emit = defineEmits(['login'])
const props = defineProps({
  loading: {
    type: Boolean,
    default: false,
  },
})

const formRef = ref(null)
const form = reactive({
  username: '',
  password: '',
})

const rules = {
  username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
  password: [{ required: true, message: '请输入密码', trigger: 'blur' }],
}

async function submit() {
  if (props.loading) return
  await formRef.value?.validate()
  emit('login', {
    username: form.username,
    password: form.password,
  })
}
</script>

<template>
  <main class="login-shell">
    <section class="login-panel">
      <div class="login-brand">
        <img class="login-brand__mark" src="/brand/wecom-agent-mark.svg" alt="数字员工" />
        <div>
          <p>Local Runtime</p>
          <h1>企微数字员工V1.0</h1>
        </div>
      </div>

      <el-form
        ref="formRef"
        :model="form"
        :rules="rules"
        class="login-form"
        label-position="top"
        @submit.prevent="submit"
      >
        <el-form-item label="用户名" prop="username">
          <el-input v-model="form.username" :prefix-icon="User" autocomplete="username" size="large" />
        </el-form-item>
        <el-form-item label="密码" prop="password">
          <el-input
            v-model="form.password"
            :prefix-icon="Lock"
            autocomplete="current-password"
            size="large"
            type="password"
            show-password
            @keyup.enter="submit"
          />
        </el-form-item>
        <el-button class="login-submit" type="primary" size="large" :loading="loading" @click="submit">
          登录控制台
        </el-button>
      </el-form>
    </section>
  </main>
</template>

// frontend/src/pages/LoginView.tsx
import { useState } from 'react';
import { Form, Input, Button, Typography } from 'antd';
import { UserOutlined, LockOutlined } from '@ant-design/icons';
import { useUserStore } from '@/store/user';
import { loginConsole } from '@/api/auth';
import brandMark from '/brand/wecom-agent-mark.svg';
import './LoginView.css';

const { Title, Text } = Typography;

interface LoginForm {
  username: string;
  password: string;
}

export default function LoginView() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const setLoginSession = useUserStore((s) => s.setLoginSession);

  const handleSubmit = async (values: LoginForm) => {
    if (loading) return;
    setError('');
    setLoading(true);

    try {
      const response = await loginConsole(values.username, values.password);
      setLoginSession(response);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : '登录失败';
      if (msg.includes('密码') || msg.includes('用户名') || msg.includes('401')) {
        setError('用户名或密码错误，请检查后重试');
      } else {
        setError(msg);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="login-shell">
      <section className="login-panel">
        <div className="login-brand">
          <img className="login-brand__mark" src={brandMark} alt="数字员工" />
          <div>
            <Text type="secondary">Local Runtime</Text>
            <Title level={1} style={{ margin: 0, fontSize: 20 }}>企微数字员工V1.0</Title>
          </div>
        </div>

        <Form<LoginForm>
          className="login-form"
          layout="vertical"
          onFinish={handleSubmit}
          autoComplete="off"
          size="large"
        >
          <Form.Item
            name="username"
            label="用户名"
            rules={[{ required: true, message: '请输入用户名' }]}
          >
            <Input prefix={<UserOutlined />} autoComplete="username" placeholder="请输入用户名" />
          </Form.Item>

          <Form.Item
            name="password"
            label="密码"
            rules={[{ required: true, message: '请输入密码' }]}
          >
            <Input.Password
              prefix={<LockOutlined />}
              autoComplete="current-password"
              placeholder="请输入密码"
              onPressEnter={() => {}}
            />
          </Form.Item>

          {error && (
            <div className="login-error">{error}</div>
          )}

          <Button
            className="login-submit"
            type="primary"
            htmlType="submit"
            loading={loading}
            block
          >
            登录控制台
          </Button>
        </Form>
      </section>
    </main>
  );
}
