// frontend/src/views/MemoryManagementView.vue
<script setup>
import { onActivated, onMounted, ref, computed, watch } from 'vue'
import { ElMessage } from 'element-plus/es/components/message/index.mjs'
import { ElMessageBox } from 'element-plus/es/components/message-box/index.mjs'
import { Search, Plus, Delete, Edit, View, Refresh } from '@element-plus/icons-vue'
import {
  getMemoryFiles,
  getMemoryItems,
  addMemoryItem,
  updateMemoryItem,
  deleteMemoryItem,
  searchMemory,
  getMemoryReviews,
  getMemoryReviewContent,
  deleteMemoryReview,
} from '../api/system'
import { formatTime, renderMarkdown } from '../utils/format'

const activeTab = ref('files')
const files = ref([])
const selectedFileKey = ref('')
const items = ref([])
const loadingFiles = ref(false)
const loadingItems = ref(false)
const searchQuery = ref('')
const searchResults = ref([])
const isSearchMode = ref(false)
const loadingSearch = ref(false)

const dialogVisible = ref(false)
const dialogMode = ref('view')
const dialogSaving = ref(false)
const dialogForm = ref({})

const expandedItemKey = ref(null)

const selectedFileLabel = computed(() => {
  const f = files.value.find(f => f.file_key === selectedFileKey.value)
  return f ? f.label : selectedFileKey.value
})

const fileGroups = computed(() => {
  const core = []
  const timeline = []
  const documents = []
  for (const f of files.value) {
    if (f.file_key.startsWith('documents/')) {
      documents.push(f)
    } else if (f.file_key.startsWith('timeline/')) {
      timeline.push(f)
    } else {
      core.push(f)
    }
  }
  const groups = []
  if (core.length) groups.push({ key: 'core', label: '核心记忆', files: core })
  if (timeline.length) groups.push({ key: 'timeline', label: '时间线', files: timeline })
  if (documents.length) groups.push({ key: 'documents', label: '文档记忆', files: documents })
  return groups
})

const displayItems = computed(() => {
  if (isSearchMode.value) {
    return searchResults.value.map(r => ({
      ...r.item,
      _file_key: r.file_key,
      _score: r.score,
      _isSearchResult: true,
    }))
  }
  return items.value
})

function contentTypeTagType(ct) {
  return {
    problem_solution: 'danger',
    qa: 'success',
    term_definition: 'primary',
    operation_guide: 'warning',
    configuration: 'info',
    process: 'danger',
    rule: 'warning',
    fact: 'primary',
    preference: 'success',
  }[ct] || 'info'
}

function priorityLabel(p) {
  if (p == null) return '-'
  const v = Number(p)
  if (v >= 10) return '紧急'
  if (v >= 6) return '高'
  if (v >= 3) return '中'
  return '低'
}

function priorityTagType(p) {
  if (p == null) return 'info'
  const v = Number(p)
  if (v >= 10) return 'danger'
  if (v >= 6) return 'warning'
  if (v >= 3) return ''
  return 'info'
}

function truncate(text, len = 120) {
  if (!text) return ''
  return text.length > len ? text.slice(0, len) + '...' : text
}

function fileLabel(fileKey) {
  const f = files.value.find(f => f.file_key === fileKey)
  return f?.label || ''
}

function displaySource(item) {
  const source = String(item?.source || '').toLowerCase()
  const sourceId = item?.source_id || ''
  const fileKey = item?._file_key || selectedFileKey.value || ''
  if (fileKey === 'explicit' || ['explicit', 'admin', 'admin_config', 'admin-config'].includes(source)) {
    return '管理员配置内容'
  }
  if (source === 'document' || fileKey.startsWith('documents/')) {
    const docKey = fileKey.startsWith('documents/') ? fileKey : sourceId ? `documents/${sourceId}` : ''
    const label = fileLabel(docKey)
    return label ? `文档《${label}》` : '文档'
  }
  return ''
}

function itemIdentity(item, fileKey = '') {
  const fk = item?._file_key || fileKey || selectedFileKey.value || ''
  return `${fk}:${item?.id || ''}`
}

async function loadFiles() {
  loadingFiles.value = true
  try {
    const result = await getMemoryFiles()
    files.value = result.files || []
    const hasSelectedFile = files.value.some(f => f.file_key === selectedFileKey.value)
    if ((!selectedFileKey.value || !hasSelectedFile) && files.value.length) {
      selectedFileKey.value = files.value[0].file_key
    } else if (!files.value.length) {
      selectedFileKey.value = ''
    }
  } catch (error) {
    ElMessage.error(error?.message || String(error))
  } finally {
    loadingFiles.value = false
  }
}

async function loadItems() {
  if (!selectedFileKey.value) {
    items.value = []
    return
  }
  loadingItems.value = true
  try {
    const result = await getMemoryItems(selectedFileKey.value)
    items.value = result.items || []
  } catch (error) {
    ElMessage.error(error?.message || String(error))
  } finally {
    loadingItems.value = false
  }
}

async function handleSearch() {
  const q = searchQuery.value.trim()
  if (!q) {
    isSearchMode.value = false
    searchResults.value = []
    return
  }
  loadingSearch.value = true
  isSearchMode.value = true
  try {
    const result = await searchMemory(q, selectedFileKey.value || '')
    searchResults.value = result.results || []
  } catch (error) {
    ElMessage.error(error?.message || String(error))
  } finally {
    loadingSearch.value = false
  }
}

function clearSearch() {
  searchQuery.value = ''
  isSearchMode.value = false
  searchResults.value = []
  expandedItemKey.value = null
}

function selectFile(fileKey) {
  selectedFileKey.value = fileKey
  expandedItemKey.value = null
  if (isSearchMode.value) {
    void handleSearch()
  }
}

function toggleExpand(item) {
  const key = itemIdentity(item)
  expandedItemKey.value = expandedItemKey.value === key ? null : key
}

function openAddDialog() {
  dialogMode.value = 'add'
  dialogForm.value = {
    _file_key: selectedFileKey.value,
    content: '',
    content_type: 'fact',
    speed_lookup: '',
    priority: 4,
    source: '',
    source_id: '',
  }
  dialogVisible.value = true
}

function openViewDialog(item, fileKey) {
  dialogMode.value = 'view'
  dialogForm.value = {
    ...item,
    _file_key: fileKey || selectedFileKey.value,
  }
  dialogVisible.value = true
}

function openEditDialog(item, fileKey) {
  dialogMode.value = 'edit'
  dialogForm.value = {
    ...item,
    _file_key: fileKey || selectedFileKey.value,
  }
  dialogVisible.value = true
}

async function handleDialogSave() {
  const fk = dialogForm.value._file_key || selectedFileKey.value
  if (!fk) {
    ElMessage.warning('未选择记忆文件')
    return
  }
  if (!dialogForm.value.content?.trim()) {
    ElMessage.warning('记忆内容不能为空')
    return
  }
  dialogSaving.value = true
  try {
    if (dialogMode.value === 'add') {
      const data = {
        content: dialogForm.value.content.trim(),
        content_type: dialogForm.value.content_type || 'fact',
        speed_lookup: dialogForm.value.speed_lookup || '',
        priority: dialogForm.value.priority ?? 4,
      }
      if (dialogForm.value.source) data.source = dialogForm.value.source
      if (dialogForm.value.source_id) data.source_id = dialogForm.value.source_id
      await addMemoryItem(fk, data)
      ElMessage.success('记忆条目已添加')
    } else if (dialogMode.value === 'edit') {
      const data = {
        content: dialogForm.value.content.trim(),
        content_type: dialogForm.value.content_type || 'fact',
        speed_lookup: dialogForm.value.speed_lookup || '',
        priority: dialogForm.value.priority ?? 4,
      }
      await updateMemoryItem(fk, dialogForm.value.id, data)
      ElMessage.success('记忆条目已更新')
    }
    dialogVisible.value = false
    await loadFiles()
    if (isSearchMode.value) {
      await handleSearch()
    } else {
      await loadItems()
    }
  } catch (error) {
    ElMessage.error(error?.message || String(error))
  } finally {
    dialogSaving.value = false
  }
}

async function handleDelete(item, fileKey) {
  const fk = fileKey || selectedFileKey.value
  try {
    await ElMessageBox.confirm(
      '确定要删除这条记忆吗？删除后不可恢复。',
      '删除确认',
      {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        type: 'warning',
      },
    )
    await deleteMemoryItem(fk, item.id)
    ElMessage.success('记忆条目已删除')
    if (expandedItemKey.value === itemIdentity(item, fk)) {
      expandedItemKey.value = null
    }
    await loadFiles()
    if (isSearchMode.value) {
      await handleSearch()
    } else {
      await loadItems()
    }
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error(error?.message || String(error))
    }
  }
}

const reviewReports = ref([])
const loadingReviews = ref(false)
const selectedReport = ref(null)
const reportContent = ref('')
const loadingReportContent = ref(false)

const reportHtml = computed(() => {
  if (!reportContent.value) return ''
  return renderMarkdown(reportContent.value)
})

const reviewGroups = computed(() => {
  const chat = []
  const document = []
  const other = []
  for (const r of reviewReports.value) {
    const t = r.report_type || 'other'
    if (t === 'chat') chat.push(r)
    else if (t === 'document') document.push(r)
    else other.push(r)
  }
  const groups = []
  if (chat.length) groups.push({ key: 'chat', label: '会话审核', reports: chat })
  if (document.length) groups.push({ key: 'document', label: '文档审核', reports: document })
  if (other.length) groups.push({ key: 'other', label: '其他审核', reports: other })
  return groups
})

async function loadReviews() {
  loadingReviews.value = true
  try {
    const result = await getMemoryReviews()
    reviewReports.value = result.reports || []
  } catch (error) {
    ElMessage.error(error?.message || String(error))
  } finally {
    loadingReviews.value = false
  }
}

async function viewReport(report) {
  selectedReport.value = report
  loadingReportContent.value = true
  try {
    const result = await getMemoryReviewContent(report.filename)
    reportContent.value = result.content || ''
  } catch (error) {
    ElMessage.error(error?.message || String(error))
  } finally {
    loadingReportContent.value = false
  }
}

async function deleteReport(report) {
  try {
    await ElMessageBox.confirm(
      '删除报告仅移除审核报告文件，不会删除已修改的记忆内容。此操作不可恢复。',
      '删除审核报告',
      {
        confirmButtonText: '删除',
        cancelButtonText: '取消',
        type: 'warning',
        confirmButtonClass: 'el-button--danger',
      },
    )
  } catch {
    return
  }
  try {
    await deleteMemoryReview(report.filename)
    ElMessage.success('审核报告已删除')
    if (selectedReport.value?.filename === report.filename) {
      selectedReport.value = null
      reportContent.value = ''
    }
    await loadReviews()
  } catch (error) {
    ElMessage.error(error?.message || String(error))
  }
}

function formatFileSize(bytes) {
  if (bytes < 1024) return bytes + ' B'
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB'
  return (bytes / (1024 * 1024)).toFixed(1) + ' MB'
}

watch(selectedFileKey, () => {
  if (!isSearchMode.value) {
    loadItems()
  }
})

onMounted(() => {
  loadFiles()
  loadReviews()
})
onActivated(() => {
  loadFiles()
  loadReviews()
  if (selectedFileKey.value) loadItems()
})
</script>

<template>
  <section class="memory-management">
    <div class="header">
      <h2>记忆管理</h2>
    </div>

    <div class="tab-bar">
      <div :class="['tab-item', { active: activeTab === 'files' }]" @click="activeTab = 'files'">记忆文件</div>
      <div :class="['tab-item', { active: activeTab === 'reviews' }]" @click="activeTab = 'reviews'">审核报告</div>
    </div>

    <div v-if="activeTab === 'files'" class="memory-layout">
      <aside class="sidebar">
        <div class="sidebar-header">
          <span class="sidebar-title">记忆文件</span>
          <el-button :icon="Refresh" circle size="small" @click="loadFiles" :loading="loadingFiles" />
        </div>
        <div class="file-list" v-loading="loadingFiles">
          <template v-for="group in fileGroups" :key="group.key">
            <div class="file-group-label">{{ group.label }}</div>
            <div
              v-for="file in group.files"
              :key="file.file_key"
              :class="['file-item', { active: selectedFileKey === file.file_key }]"
              @click="selectFile(file.file_key)"
            >
              <div class="file-info">
                <span class="file-label">{{ file.label }}</span>
                <span class="file-key">{{ file.file_key }}</span>
              </div>
              <el-badge :value="file.item_count || 0" :type="selectedFileKey === file.file_key ? 'primary' : 'info'" />
            </div>
          </template>
          <div v-if="!files.length && !loadingFiles" class="empty-sidebar">暂无记忆文件</div>
        </div>
      </aside>

      <main class="main-area">
        <div class="toolbar">
          <div class="search-bar">
            <el-input
              v-model="searchQuery"
              placeholder="搜索记忆内容..."
              clearable
              :prefix-icon="Search"
              @keyup.enter="handleSearch"
              @clear="clearSearch"
              style="max-width: 400px"
            />
            <el-button type="primary" :icon="Search" @click="handleSearch" :loading="loadingSearch">搜索</el-button>
            <el-button v-if="isSearchMode" @click="clearSearch">退出搜索</el-button>
          </div>
          <div class="toolbar-actions">
            <el-button type="primary" :icon="Plus" @click="openAddDialog" :disabled="!selectedFileKey">新增条目</el-button>
          </div>
        </div>

        <div v-if="isSearchMode" class="search-hint">
          <el-tag type="warning" size="large">搜索模式</el-tag>
          <span>共找到 {{ searchResults.length }} 条结果</span>
        </div>

        <div class="items-area" v-loading="loadingItems || loadingSearch">
          <div v-if="!displayItems.length && !(loadingItems || loadingSearch)" class="empty-items">
            {{ isSearchMode ? '未找到匹配的记忆条目' : '该文件暂无记忆条目' }}
          </div>

          <div
            v-for="item in displayItems"
            :key="itemIdentity(item)"
            :class="['item-card', { expanded: expandedItemKey === itemIdentity(item) }]"
          >
            <div class="item-header" @click="toggleExpand(item)">
              <div class="item-meta">
                <el-tag :type="contentTypeTagType(item.content_type)" size="small">{{ item.content_type || '未分类' }}</el-tag>
                <el-tag v-if="item.priority != null" :type="priorityTagType(item.priority)" size="small">P{{ item.priority }} {{ priorityLabel(item.priority) }}</el-tag>
                <el-tag v-if="item._isSearchResult" type="warning" size="small">{{ item._file_key }}</el-tag>
                <span v-if="item.speed_lookup" class="speed-lookup">{{ truncate(item.speed_lookup, 40) }}</span>
              </div>
              <div class="item-actions" @click.stop>
                <el-button :icon="View" size="small" text @click="openViewDialog(item, item._file_key)" />
                <el-button :icon="Edit" size="small" text @click="openEditDialog(item, item._file_key)" />
                <el-button :icon="Delete" size="small" text type="danger" @click="handleDelete(item, item._file_key)" />
              </div>
            </div>
            <div class="item-content">
              <span v-if="expandedItemKey !== itemIdentity(item)">{{ truncate(item.content, 200) }}</span>
              <pre v-else class="item-content-full">{{ item.content }}</pre>
            </div>
            <div class="item-footer">
              <span v-if="displaySource(item)" class="item-source">来源: {{ displaySource(item) }}</span>
              <span class="item-time">{{ formatTime(item.created_at) }}</span>
            </div>
          </div>
        </div>
      </main>
    </div>

    <div v-if="activeTab === 'reviews'" class="reviews-panel">
      <div class="reviews-list" v-loading="loadingReviews">
        <div v-if="!reviewReports.length && !loadingReviews" class="empty-items">暂无审核报告</div>
        <template v-for="group in reviewGroups" :key="group.key">
          <div class="review-group-label">{{ group.label }}</div>
          <div
            v-for="report in group.reports"
            :key="report.filename"
            :class="['review-card', { active: selectedReport?.filename === report.filename }]"
            @click="viewReport(report)"
          >
            <div class="review-card-info">
              <span class="review-card-name">{{ report.filename }}</span>
              <span class="review-card-meta">{{ formatFileSize(report.size) }} · {{ formatTime(report.modified_at) }}</span>
            </div>
          </div>
        </template>
      </div>
      <div class="review-content" v-loading="loadingReportContent">
        <div v-if="!selectedReport" class="empty-items">选择左侧报告查看内容</div>
        <template v-else>
          <div class="review-content-header">
            <span class="review-content-filename">{{ selectedReport.filename }}</span>
            <el-button :icon="Delete" size="small" text type="danger" @click="deleteReport(selectedReport)">删除</el-button>
          </div>
          <div class="review-content-text markdown-body" v-html="reportHtml"></div>
        </template>
      </div>
    </div>

    <el-dialog v-model="dialogVisible" :title="dialogMode === 'add' ? '新增记忆条目' : dialogMode === 'edit' ? '编辑记忆条目' : '记忆条目详情'" width="700px" :close-on-click-modal="false">
      <el-form :model="dialogForm" label-width="100px">
        <el-form-item label="记忆文件">
          <template v-if="dialogMode === 'add'">
            <el-select v-model="dialogForm._file_key" placeholder="选择记忆文件" style="width: 100%">
              <el-option v-for="f in files" :key="f.file_key" :label="f.label" :value="f.file_key" />
            </el-select>
          </template>
          <template v-else>
            <el-tag>{{ dialogForm._file_key }}</el-tag>
          </template>
        </el-form-item>
        <el-form-item label="内容">
          <template v-if="dialogMode !== 'view'">
            <el-input v-model="dialogForm.content" type="textarea" :rows="8" placeholder="输入记忆内容" />
          </template>
          <template v-else>
            <pre class="dialog-content-view">{{ dialogForm.content }}</pre>
          </template>
        </el-form-item>
        <el-form-item label="内容类型">
          <template v-if="dialogMode !== 'view'">
            <el-select v-model="dialogForm.content_type" style="width: 200px">
              <el-option label="事实 (fact)" value="fact" />
              <el-option label="偏好 (preference)" value="preference" />
              <el-option label="问题方案 (problem_solution)" value="problem_solution" />
              <el-option label="问答 (qa)" value="qa" />
              <el-option label="术语定义 (term_definition)" value="term_definition" />
              <el-option label="操作指南 (operation_guide)" value="operation_guide" />
              <el-option label="配置 (configuration)" value="configuration" />
              <el-option label="流程 (process)" value="process" />
              <el-option label="规则 (rule)" value="rule" />
            </el-select>
          </template>
          <template v-else>
            <el-tag :type="contentTypeTagType(dialogForm.content_type)">{{ dialogForm.content_type || '未分类' }}</el-tag>
          </template>
        </el-form-item>
        <el-form-item label="快速检索">
          <template v-if="dialogMode !== 'view'">
            <el-input v-model="dialogForm.speed_lookup" placeholder="简短摘要，用于快速检索" maxlength="200" />
          </template>
          <template v-else>{{ dialogForm.speed_lookup || '-' }}</template>
        </el-form-item>
        <el-form-item label="优先级">
          <template v-if="dialogMode !== 'view'">
            <el-select v-model="dialogForm.priority" style="width: 200px">
              <el-option label="低 (2)" :value="2" />
              <el-option label="中 (4)" :value="4" />
              <el-option label="高 (6)" :value="6" />
              <el-option label="工作 (8)" :value="8" />
              <el-option label="紧急 (10)" :value="10" />
            </el-select>
          </template>
          <template v-else>
            <el-tag :type="priorityTagType(dialogForm.priority)">P{{ dialogForm.priority }} {{ priorityLabel(dialogForm.priority) }}</el-tag>
          </template>
        </el-form-item>
        <template v-if="dialogMode === 'view'">
          <el-form-item label="来源">{{ displaySource(dialogForm) || '-' }}</el-form-item>
          <el-form-item label="来源ID">{{ dialogForm.source_id || '-' }}</el-form-item>
          <el-form-item label="创建时间">{{ formatTime(dialogForm.created_at) || '-' }}</el-form-item>
          <el-form-item label="更新时间">{{ formatTime(dialogForm.updated_at) || '-' }}</el-form-item>
        </template>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button @click="dialogVisible = false">{{ dialogMode === 'view' ? '关闭' : '取消' }}</el-button>
          <el-button v-if="dialogMode !== 'view'" type="primary" :loading="dialogSaving" @click="handleDialogSave">保存</el-button>
        </div>
      </template>
    </el-dialog>
  </section>
</template>

// frontend/src/pages/memory-management-view/MemoryManagementView.tsx
import { useEffect, useState, useCallback, useRef } from 'react';
import { Table, Tag, Button, Modal, Input, Select, Tabs, Space, message, Empty, Popconfirm, Row, Col } from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined, EyeOutlined, ReloadOutlined } from '@ant-design/icons';
import { getMemoryFiles, getMemoryItems, addMemoryItem, updateMemoryItem, deleteMemoryItem, searchMemory, getMemoryReviews, getMemoryReviewContent, deleteMemoryReview } from '@/api/system';
import { formatTime } from '@/utils/format';
import type { ColumnsType } from 'antd/es/table';

interface MemoryItem {
  id: string;
  content: string;
  content_type?: string;
  priority?: number;
  source?: string;
  source_id?: string;
  speed_lookup?: string;
  created_at?: string;
  _file_key?: string;
  _score?: number;
  _isSearchResult?: boolean;
}

interface MemoryFile {
  file_key: string;
  label: string;
  item_count?: number;
}

interface Review {
  filename: string;
  created_at?: string;
  status?: string;
}

function ctColor(ct?: string) {
  const m: Record<string, string> = { problem_solution: 'red', qa: 'green', term_definition: 'blue', operation_guide: 'orange', configuration: 'default', process: 'red', rule: 'orange', fact: 'blue', preference: 'green' };
  return m[ct || ''] || 'default';
}

function priorityLabel(p?: number) {
  if (p == null) return '-';
  if (p >= 10) return '紧急';
  if (p >= 6) return '高';
  if (p >= 3) return '中';
  return '低';
}

function priorityColor(p?: number) {
  if (p == null) return 'default';
  if (p >= 10) return 'red';
  if (p >= 6) return 'orange';
  if (p >= 3) return 'default';
  return 'default';
}

export default function MemoryManagementView() {
  const [files, setFiles] = useState<MemoryFile[]>([]);
  const [selectedFile, setSelectedFile] = useState('');
  const [items, setItems] = useState<MemoryItem[]>([]);
  const [loadingItems, setLoadingItems] = useState(false);
  const [searchQ, setSearchQ] = useState('');
  const [searchResults, setSearchResults] = useState<MemoryItem[]>([]);
  const [isSearchMode, setIsSearchMode] = useState(false);
  const [searchLoading, setSearchLoading] = useState(false);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [dialogMode, setDialogMode] = useState<'add' | 'edit' | 'view'>('view');
  const [dialogForm, setDialogForm] = useState<MemoryItem>({ id: '', content: '', content_type: 'fact', priority: 4, source: '', speed_lookup: '' });
  const [dialogSaving, setDialogSaving] = useState(false);
  const [reviews, setReviews] = useState<Review[]>([]);
  const [reviewContent, setReviewContent] = useState('');
  const [reviewOpen, setReviewOpen] = useState(false);

  const fileGroups = (() => {
    const core: MemoryFile[] = [], timeline: MemoryFile[] = [], documents: MemoryFile[] = [];
    files.forEach((f) => {
      if (f.file_key.startsWith('documents/')) documents.push(f);
      else if (f.file_key.startsWith('timeline/')) timeline.push(f);
      else core.push(f);
    });
    return [
      ...(core.length ? [{ key: 'core', label: '核心记忆', files: core }] : []),
      ...(timeline.length ? [{ key: 'timeline', label: '时间线', files: timeline }] : []),
      ...(documents.length ? [{ key: 'documents', label: '文档记忆', files: documents }] : []),
    ];
  })();

  const loadFiles = useCallback(async () => {
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const result: any = await getMemoryFiles();
      const fls = result.files || [];
      setFiles(fls);
      if ((!selectedFile || !fls.some((f: MemoryFile) => f.file_key === selectedFile)) && fls.length) {
        setSelectedFile(fls[0].file_key);
      }
    } catch (e) { message.error(String(e)); }
  }, [selectedFile]);

  const loadItems = useCallback(async () => {
    if (!selectedFile) { setItems([]); return; }
    setLoadingItems(true);
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const result: any = await getMemoryItems(selectedFile);
      setItems(result.items || []);
    } catch (e) { message.error(String(e)); }
    finally { setLoadingItems(false); }
  }, [selectedFile]);

  useEffect(() => { loadFiles(); }, []); // eslint-disable-line

  const itemsMounted = useRef(false);
  useEffect(() => {
    if (!isSearchMode) {
      itemsMounted.current = true;
      // eslint-disable-next-line react-hooks/set-state-in-effect
      loadItems();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedFile, isSearchMode]);

  const handleSearch = async () => {
    const q = searchQ.trim();
    if (!q) { setIsSearchMode(false); setSearchResults([]); return; }
    setSearchLoading(true); setIsSearchMode(true);
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const result: any = await searchMemory(q, selectedFile || '');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      setSearchResults((result.results || []).map((r: any) => ({ ...r.item, _file_key: r.file_key, _score: r.score, _isSearchResult: true })));
    } catch (e) { message.error(String(e)); }
    finally { setSearchLoading(false); }
  };

  const displayItems = isSearchMode ? searchResults : items;

  const openAdd = () => {
    setDialogMode('add');
    setDialogForm({ id: '', content: '', content_type: 'fact', priority: 4, source: '', speed_lookup: '', _file_key: selectedFile });
    setDialogOpen(true);
  };

  const openView = (item: MemoryItem) => { setDialogMode('view'); setDialogForm(item); setDialogOpen(true); };
  const openEdit = (item: MemoryItem) => { setDialogMode('edit'); setDialogForm(item); setDialogOpen(true); };

  const handleSave = async () => {
    if (!dialogForm.content?.trim()) { message.warning('记忆内容不能为空'); return; }
    setDialogSaving(true);
    try {
      if (dialogMode === 'add') {
        await addMemoryItem(selectedFile, dialogForm as unknown as Record<string, unknown>);
        message.success('记忆已添加');
      } else {
        await updateMemoryItem(dialogForm._file_key || selectedFile, dialogForm.id, dialogForm as unknown as Record<string, unknown>);
        message.success('记忆已更新');
      }
      setDialogOpen(false);
      loadItems();
    } catch (e) { message.error(String(e)); }
    finally { setDialogSaving(false); }
  };

  const handleDelete = async (item: MemoryItem) => {
    await deleteMemoryItem(item._file_key || selectedFile, item.id);
    message.success('记忆已删除');
    loadItems();
  };

  const loadReviews = async () => {
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const result: any = await getMemoryReviews();
      setReviews(result.reviews || []);
    } catch (e) { message.error(String(e)); }
  };

  const viewReview = async (filename: string) => {
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const result: any = await getMemoryReviewContent(filename);
      setReviewContent(result.content || String(result));
      setReviewOpen(true);
    } catch (e) { message.error(String(e)); }
  };

  const handleDeleteReview = async (filename: string) => {
    await deleteMemoryReview(filename);
    message.success('审核报告已删除');
    loadReviews();
  };

  const columns: ColumnsType<MemoryItem> = [
    { title: 'ID', dataIndex: 'id', width: 60, responsive: ['md'] },
    { title: '类型', dataIndex: 'content_type', width: 90, render: (v: string) => <Tag color={ctColor(v)}>{v || '-'}</Tag> },
    { title: '内容', dataIndex: 'content', ellipsis: true, render: (v: string) => v?.length > 120 ? v.slice(0, 120) + '...' : v },
    { title: '优先级', dataIndex: 'priority', width: 80, render: (v: number) => <Tag color={priorityColor(v)}>{priorityLabel(v)}</Tag> },
    { title: '操作', width: 160, render: (_, r) => (
      <Space>
        <Button size="small" type="link" icon={<EyeOutlined />} onClick={() => openView(r)}>查看</Button>
        <Button size="small" type="link" icon={<EditOutlined />} onClick={() => openEdit(r)}>编辑</Button>
        <Popconfirm title="确定删除此记忆？" onConfirm={() => handleDelete(r)}><Button size="small" type="link" danger icon={<DeleteOutlined />} /></Popconfirm>
      </Space>
    )},
  ];

  return (
    <section>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
        <h2 style={{ margin: 0 }}>记忆管理</h2>
        <Space>
          <Input.Search value={searchQ} onChange={(e) => setSearchQ(e.target.value)} onSearch={handleSearch} placeholder="搜索记忆内容" style={{ width: 240 }} loading={searchLoading} />
          {isSearchMode && <Button onClick={() => { setSearchQ(''); setIsSearchMode(false); }}>清除</Button>}
          <Button icon={<ReloadOutlined />} onClick={() => { loadFiles(); loadItems(); }}>刷新</Button>
          <Button type="primary" icon={<PlusOutlined />} onClick={openAdd} disabled={!selectedFile}>新增记忆</Button>
        </Space>
      </div>

      <Tabs defaultActiveKey="items" onChange={(key) => { if (key === 'reviews') loadReviews(); }} items={[
        {
          key: 'items', label: '记忆条目',
          children: (
            <Row gutter={16}>
              <Col xs={24} md={6}>
                <div style={{ fontWeight: 600, marginBottom: 8, fontSize: 13, color: '#6b7280' }}>记忆文件</div>
                {fileGroups.map((group) => (
                  <div key={group.key} style={{ marginBottom: 12 }}>
                    <div style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', color: '#9ca3af', marginBottom: 4 }}>{group.label}</div>
                    {group.files.map((f) => (
                      <div key={f.file_key} onClick={() => setSelectedFile(f.file_key)}
                        style={{ padding: '6px 10px', cursor: 'pointer', borderRadius: 6, fontSize: 13, background: selectedFile === f.file_key ? '#eff6ff' : 'transparent', color: selectedFile === f.file_key ? '#3b82f6' : '#374151', fontWeight: selectedFile === f.file_key ? 600 : 400, marginBottom: 2 }}>
                        {f.label} <span style={{ color: '#9ca3af', fontSize: 11 }}>({f.item_count || 0})</span>
                      </div>
                    ))}
                  </div>
                ))}
              </Col>
              <Col xs={24} md={18}>
                <Table<MemoryItem> columns={columns} dataSource={displayItems}
                  rowKey={(r) => `${r._file_key || ''}:${r.id}`}
                  loading={loadingItems || searchLoading} size="small" scroll={{ x: 700 }}
                  locale={{ emptyText: <Empty description="暂无记忆条目" /> }}
                  pagination={{ pageSize: 20, showSizeChanger: true }} />
              </Col>
            </Row>
          ),
        },
        {
          key: 'reviews', label: '审核报告',
          children: reviews.length === 0 ? <Empty description="暂无审核报告" /> : (
            <Table<Review> dataSource={reviews} rowKey="filename" size="small"
              columns={[
                { title: '文件名', dataIndex: 'filename', ellipsis: true },
                { title: '状态', dataIndex: 'status', width: 100, render: (v: string) => <Tag>{v || '-'}</Tag> },
                { title: '创建时间', dataIndex: 'created_at', width: 180, render: (v: string) => formatTime(v) },
                { title: '操作', width: 160, render: (_, r) => (
                  <Space>
                    <Button size="small" type="link" onClick={() => viewReview(r.filename)}>查看</Button>
                    <Popconfirm title="确定删除？" onConfirm={() => handleDeleteReview(r.filename)}><Button size="small" type="link" danger>删除</Button></Popconfirm>
                  </Space>
                )},
              ]} pagination={{ pageSize: 20 }} />
          ),
        },
      ]} />

      {/* Add/Edit/View Dialog */}
      <Modal title={dialogMode === 'add' ? '新增记忆' : dialogMode === 'edit' ? '编辑记忆' : '查看记忆'}
        open={dialogOpen} onCancel={() => setDialogOpen(false)} width={640}
        footer={dialogMode === 'view' ? [<Button key="close" onClick={() => setDialogOpen(false)}>关闭</Button>] : [
          <Button key="cancel" onClick={() => setDialogOpen(false)}>取消</Button>,
          <Button key="save" type="primary" loading={dialogSaving} onClick={handleSave}>保存</Button>,
        ]}>
        <div style={{ marginBottom: 12 }}>
          <label style={{ display: 'block', marginBottom: 4, fontSize: 13, fontWeight: 500 }}>内容</label>
          <Input.TextArea value={dialogForm.content} disabled={dialogMode === 'view'} rows={6}
            onChange={(e) => setDialogForm((f) => ({ ...f, content: e.target.value }))} />
        </div>
        <Row gutter={12}>
          <Col span={12}>
            <label style={{ fontSize: 13, fontWeight: 500 }}>类型</label>
            <Select value={dialogForm.content_type} disabled={dialogMode === 'view'} style={{ width: '100%' }}
              onChange={(v) => setDialogForm((f) => ({ ...f, content_type: v }))}
              options={['fact', 'qa', 'preference', 'problem_solution', 'operation_guide', 'configuration', 'process', 'rule', 'term_definition'].map((v) => ({ value: v, label: v }))} />
          </Col>
          <Col span={12}>
            <label style={{ fontSize: 13, fontWeight: 500 }}>优先级 (1-10)</label>
            <Input type="number" min={1} max={10} value={dialogForm.priority} disabled={dialogMode === 'view'}
              onChange={(e) => setDialogForm((f) => ({ ...f, priority: Number(e.target.value) }))} />
          </Col>
        </Row>
      </Modal>

      {/* Review Content Modal */}
      <Modal title="审核报告" open={reviewOpen} onCancel={() => setReviewOpen(false)} footer={null} width={800}>
        <pre style={{ whiteSpace: 'pre-wrap', maxHeight: 500, overflow: 'auto', background: '#f5f5f5', padding: 16, borderRadius: 6, fontSize: 13 }}>
          {reviewContent}
        </pre>
      </Modal>
    </section>
  );
}
