// frontend/src/pages/control-view/ControlView.tsx
import { useEffect, useRef, useState, useCallback } from 'react';
import { Card, Tag, Button, message } from 'antd';
import { PlayCircleOutlined, PauseCircleOutlined } from '@ant-design/icons';
import { useRuntimeStore } from '@/store/runtime';
import { getAiStatus, cancelAiWork, clearAiWork, type AiStatus, type AiTask } from '@/api/agents';
import { fetchWithAuth } from '@/utils/request';
import type { Bot } from '@/api/bots';
import { getAgentLabel, formatTimeOnly } from '@/utils/format';

function stageLabel(stage?: string): string {
  const map: Record<string, string> = {
    '接收消息': '接收消息',
    '等待 Agent 并发槽': '等待并发槽',
    '构建上下文并调用 Agent（流式）': 'Agent 推理中',
    '构建上下文并调用 Agent': 'Agent 推理中',
    '发送企微回复': '发送回复',
    '完成': '完成',
    '已截断': '已截断',
    '异常截断': '异常截断',
  };
  return map[stage || ''] || stage || '--';
}

function statusTagColor(status: string): string {
  if (status === 'running') return 'blue';
  if (status === 'completed') return 'green';
  if (status === 'failed') return 'red';
  if (status === 'cancelled' || status === 'cancel_requested') return 'orange';
  return 'default';
}

function isActiveStatus(status: string): boolean {
  return ['queued', 'running', 'cancel_requested'].includes(status);
}

function taskDisplayName(task: AiTask): string {
  const convName = task.conv_display_name || '';
  const chatType = task.conv_chat_type || '';
  const senderName = task.conv_sender_name || '';
  if (chatType === 'group' && convName) {
    return senderName ? `${convName}:${senderName}` : convName;
  }
  if (senderName) return senderName;
  if (convName) return convName;
  return task.chat_name || task.chat_id || '--';
}

function reasoningPreview(task: AiTask): string {
  const reasoning = String(task?.reasoning || '').trim();
  if (reasoning) return reasoning;
  const stage = stageLabel(task?.stage || '');
  if (isActiveStatus(task?.status)) {
    return stage ? `当前阶段：${stage}` : 'Agent 正在工作...';
  }
  return task?.error ? `异常：${task.error}` : '暂无思考链记录';
}

function getBotAgentProvider(bot: Bot): string {
  return typeof bot.agent_provider === 'string' ? bot.agent_provider : '';
}

function getBotMetricCount(value: unknown): number {
  return typeof value === 'number' ? value : 0;
}

function getBotPrompt(bot: Bot): string {
  return typeof bot.system_prompt === 'string' ? bot.system_prompt : '';
}

export default function ControlView() {
  const {
    bots, agents, botStatuses, startingBots, stoppingBots,
    handleStartBot, handleStopBot, loadBots, loadAgents,
  } = useRuntimeStore();

  const [aiStatus, setAiStatus] = useState<AiStatus>({ busy: false, active: [], recent: [] });
  const [cancellingTasks, setCancellingTasks] = useState<Set<string>>(new Set());
  const [clearingTasks, setClearingTasks] = useState<Set<string>>(new Set());
  const controllerRef = useRef<AbortController | null>(null);
  const reconnectTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const streamStoppedRef = useRef(false);
  const startStreamRef = useRef<() => Promise<void>>(async () => {});

  const enabledBots = bots.filter((bot) => Boolean(bot.is_active));

  const getStatus = useCallback((botKey: string) => {
    return botStatuses[botKey] || { running: false, pid: null };
  }, [botStatuses]);

  const combinedTasks = (() => {
    const tasks = [...(aiStatus.active || []), ...(aiStatus.recent || [])];
    const seen = new Set<string>();
    const unique: AiTask[] = [];
    for (const task of tasks) {
      if (task?.trace_id && !seen.has(task.trace_id)) {
        seen.add(task.trace_id);
        unique.push(task);
      }
    }
    return unique.slice(0, 15);
  })();

  // SSE stream for AI status
  const closeStream = useCallback(() => {
    if (controllerRef.current) {
      controllerRef.current.abort();
      controllerRef.current = null;
    }
  }, []);

  const startStream = useCallback(async () => {
    closeStream();
    const controller = new AbortController();
    controllerRef.current = controller;
    try {
      const response = await fetchWithAuth('/ai/status/stream', {
        headers: { Accept: 'text/event-stream' },
        signal: controller.signal,
      });
      if (!response.ok || !response.body) return;
      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';
      while (!controller.signal.aborted) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        let frameEnd = buffer.indexOf('\n\n');
        while (frameEnd !== -1) {
          const frame = buffer.slice(0, frameEnd);
          buffer = buffer.slice(frameEnd + 2);
          const dataLine = frame.split(/\r?\n/).find((line) => line.startsWith('data:'));
          if (dataLine) {
            try {
              setAiStatus(JSON.parse(dataLine.slice(5).trim()));
            } catch { /* ignore malformed frames */ }
          }
          frameEnd = buffer.indexOf('\n\n');
        }
      }
    } catch {
      if (!controller.signal.aborted && !streamStoppedRef.current) {
        reconnectTimerRef.current = setTimeout(() => startStreamRef.current(), 3000);
      }
    } finally {
      if (controllerRef.current === controller) {
        controllerRef.current = null;
      }
    }
  }, [closeStream]);

  // Keep ref in sync
  useEffect(() => {
    startStreamRef.current = startStream;
  });

  useEffect(() => {
    streamStoppedRef.current = false;
    loadBots();
    loadAgents();
    getAiStatus().then((data) => setAiStatus(data)).catch(() => setAiStatus({ busy: false, active: [], recent: [] }));
    startStreamRef.current();

    return () => {
      streamStoppedRef.current = true;
      closeStream();
      if (reconnectTimerRef.current) {
        clearTimeout(reconnectTimerRef.current);
      }
    };
  }, [loadBots, loadAgents, startStream, closeStream]);

  const handleCancel = async (traceId: string) => {
    if (cancellingTasks.has(traceId)) return;
    const next = new Set(cancellingTasks);
    next.add(traceId);
    setCancellingTasks(next);
    try {
      await cancelAiWork(traceId);
      message.success('已发送取消请求');
      const status = await getAiStatus();
      setAiStatus(status);
    } catch (e) {
      message.error(String(e));
    } finally {
      const s = new Set(cancellingTasks);
      s.delete(traceId);
      setCancellingTasks(s);
    }
  };

  const handleClear = async (traceId: string) => {
    if (clearingTasks.has(traceId)) return;
    const next = new Set(clearingTasks);
    next.add(traceId);
    setClearingTasks(next);
    try {
      await clearAiWork(traceId);
      message.success('已清除任务');
      const status = await getAiStatus();
      setAiStatus(status);
    } catch (e) {
      message.error(String(e));
    } finally {
      const s = new Set(clearingTasks);
      s.delete(traceId);
      setClearingTasks(s);
    }
  };

  return (
    <section style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1.45fr) minmax(320px, 0.8fr)', gap: 24, height: '100%', minHeight: 0, alignItems: 'start' }}>
      {/* Bot Cards Panel */}
      <Card
        className="panel"
        title={<div className="panel-title split"><span>已启用 Bot</span></div>}
        styles={{ body: { padding: 24, display: 'flex', flexDirection: 'column', gap: 20, overflow: 'auto', maxHeight: 'calc(100vh - 200px)' } }}
      >
        {enabledBots.length > 0 ? (
          <div className="bot-card-grid">
            {enabledBots.map((bot) => {
              const status = getStatus(bot.bot_key);
              return (
                <article key={bot.bot_key} className="bot-service-card" style={{ display: 'grid', gap: 16, padding: 18, border: '1px solid #e5e7eb', borderRadius: 12, background: '#f9fafb' }}>
                  <header style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 }}>
                    <div>
                      <h3 style={{ margin: 0, color: '#111827', fontSize: 18 }}>{String(bot.name || bot.bot_key)}</h3>
                      <p style={{ margin: '4px 0 0', color: '#6b7280', fontSize: 13 }}>{getAgentLabel(getBotAgentProvider(bot), agents)}</p>
                    </div>
                    <Tag color={status.running ? 'green' : 'default'}>{status.running ? '运行中' : '已停止'}</Tag>
                  </header>

                  <div className="metric-row metric-row--bot" style={{ gridTemplateColumns: 'repeat(3, minmax(0, 1fr))' }}>
                    <div><span>MCP 数</span><strong>{getBotMetricCount(bot.enabled_mcp_count)}</strong></div>
                    <div><span>Skills 数</span><strong>{getBotMetricCount(bot.enabled_skill_count)}</strong></div>
                    <div><span>PID</span><strong>{status.pid || '-'}</strong></div>
                  </div>

                  <div className="prompt-preview" style={{ padding: '14px 16px', border: '1px solid #e5e7eb', borderRadius: 12, background: '#f9fafb' }}>
                    <span style={{ display: 'block', marginBottom: 6, color: '#6b7280', fontSize: 12, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.02em' }}>提示词</span>
                    <p style={{ margin: 0, color: '#111827', lineHeight: 1.7, display: '-webkit-box', WebkitLineClamp: 3, WebkitBoxOrient: 'vertical', overflow: 'hidden', textOverflow: 'ellipsis', wordBreak: 'break-word' }}
                       title={getBotPrompt(bot)}>
                      {getBotPrompt(bot).trim() || '未设置提示词'}
                    </p>
                  </div>

                  <footer className="actions" style={{ justifyContent: 'flex-end' }}>
                    <Button
                      type="primary"
                      icon={<PlayCircleOutlined />}
                      disabled={status.running || startingBots.has(bot.bot_key)}
                      loading={startingBots.has(bot.bot_key)}
                      onClick={() => handleStartBot(bot.bot_key)}
                      style={{ background: '#10b981', borderColor: '#10b981' }}
                    >
                      启动服务
                    </Button>
                    <Button
                      danger
                      icon={<PauseCircleOutlined />}
                      disabled={!status.running || stoppingBots.has(bot.bot_key)}
                      loading={stoppingBots.has(bot.bot_key)}
                      onClick={() => handleStopBot(bot.bot_key)}
                    >
                      停止服务
                    </Button>
                  </footer>
                </article>
              );
            })}
          </div>
        ) : (
          <div className="empty-block" style={{ padding: '28px 24px', textAlign: 'center' }}>
            <strong>暂无已启用 Bot</strong>
            <span>请先在 Bot 配置页面启用 Bot，再回到工作台查看运行状态。</span>
          </div>
        )}
      </Card>

      {/* Task List Panel */}
      <Card
        className="panel"
        title={
          <div className="panel-title split" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span>任务列表</span>
            {aiStatus.busy && <Tag color="orange">运行中</Tag>}
          </div>
        }
        styles={{ body: { padding: 24, display: 'flex', flexDirection: 'column', gap: 10, overflow: 'auto', maxHeight: 'calc(100vh - 200px)' } }}
      >
        {combinedTasks.length > 0 ? (
          <div className="task-list" style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {combinedTasks.map((task) => (
              <article key={task.trace_id} className={`task-item ${isActiveStatus(task.status) ? 'task-item--active' : ''}`}
                style={{
                  padding: '12px 14px', border: `1px solid ${isActiveStatus(task.status) ? '#3b82f6' : '#e5e7eb'}`,
                  borderRadius: 10, background: isActiveStatus(task.status) ? '#eff6ff' : '#f9fafb',
                  display: 'flex', flexDirection: 'column', gap: 6,
                }}>
                <div className="task-item__head" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 }}>
                  <strong style={{ fontSize: 14, color: '#111827', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{taskDisplayName(task)}</strong>
                  <Tag color={statusTagColor(task.status)}>{stageLabel(task.stage)}</Tag>
                </div>
                <p className="task-item__question" style={{ color: '#6b7280', fontSize: 13, margin: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                  {(task.question || '').slice(0, 100)}
                </p>
                <pre className="task-item__answer" style={{
                  margin: 0, padding: '10px 12px', color: '#0f172a', background: 'rgba(255,255,255,0.78)',
                  border: '1px solid rgba(59,130,246,0.18)', borderRadius: 8, fontSize: 12,
                  lineHeight: 1.6, whiteSpace: 'pre-wrap', wordBreak: 'break-word', maxHeight: 140, overflow: 'auto',
                }}>
                  {reasoningPreview(task)}
                </pre>
                <div className="task-item__meta" style={{ display: 'flex', alignItems: 'center', gap: 12, color: '#9ca3af', fontSize: 12 }}>
                  <span>TraceId: {task.trace_id.slice(0, 8)}...</span>
                  <span>{formatTimeOnly(task.started_at)}</span>
                  {isActiveStatus(task.status) ? (
                    <Button size="small" type="link" danger
                      loading={cancellingTasks.has(task.trace_id)}
                      disabled={cancellingTasks.has(task.trace_id)}
                      onClick={() => handleCancel(task.trace_id)}>
                      取消
                    </Button>
                  ) : (
                    <Button size="small" type="link"
                      loading={clearingTasks.has(task.trace_id)}
                      disabled={clearingTasks.has(task.trace_id)}
                      onClick={() => handleClear(task.trace_id)}>
                      清除
                    </Button>
                  )}
                </div>
              </article>
            ))}
          </div>
        ) : (
          <div className="empty-block empty-block--large" style={{ minHeight: 260, display: 'grid', gap: 8, placeItems: 'center', padding: '28px 24px', textAlign: 'center' }}>
            <strong>暂无任务</strong>
            <span>Bot 运行后，Agent 的调用任务会实时展示在这里。</span>
          </div>
        )}
      </Card>
    </section>
  );
}

// backend-agent/web/src/views/ControlView.vue
<script setup>
import { computed, onActivated, onBeforeUnmount, onDeactivated, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus/es/components/message/index.mjs'
import { VideoPause, VideoPlay } from '@element-plus/icons-vue'
import { getAiStatus, cancelAiWork, clearAiWork } from '../api/runtime'
import { fetchWithAuth } from '../api/http'
import { getAgentLabel, formatTimeOnly } from '../utils/format'

const props = defineProps({
    agents: {
        type: Array,
        default: () => [],
    },
    bots: {
        type: Array,
        default: () => [],
    },
    botStatuses: {
        type: Object,
        default: () => ({}),
    },
    startingBots: {
        type: Set,
        default: () => new Set(),
    },
    stoppingBots: {
        type: Set,
        default: () => new Set(),
    },
})

const combinedTasks = computed(() => {
  // 确保先显示 active（包括 cancel_requested），然后显示 recent
  const tasks = [...(aiStatus.value.active || []), ...(aiStatus.value.recent || [])]
  const seen = new Set()
  const unique = []
  for (const task of tasks) {
    if (task?.trace_id && !seen.has(task.trace_id)) {
      seen.add(task.trace_id)
      unique.push(task)
    }
  }
  return unique.slice(0, 15)
})

function isActiveStatus(status) {
  return ['queued', 'running', 'cancel_requested'].includes(status)
}

const emit = defineEmits(['start-bot', 'stop-bot'])

const enabledBots = computed(() => props.bots.filter((bot) => Boolean(bot.is_active)))

const aiStatus = ref({ busy: false, active: [], recent: [] })
let aiStatusController = null
let reconnectTimer = null
let streamStopped = false
const cancellingTasks = ref(new Set())
const clearingTasks = ref(new Set())

function isCancelling(traceId) {
  return cancellingTasks.value.has(traceId)
}

function isClearing(traceId) {
  return clearingTasks.value.has(traceId)
}

function getStatus(botKey) {
  return props.botStatuses[botKey] || { running: false, pid: null }
}

function promptPreview(prompt) {
  const text = String(prompt || '').trim()
  return text || '未设置提示词'
}

async function loadAiStatus() {
  try {
    aiStatus.value = await getAiStatus()
  } catch {
    aiStatus.value = { busy: false, active: [], recent: [] }
  }
}

async function handleCancel(traceId) {
    if (cancellingTasks.value.has(traceId)) {
        return
    }
    cancellingTasks.value.add(traceId)
    try {
        await cancelAiWork(traceId)
        ElMessage.success('已发送取消请求')
        await loadAiStatus()
    } catch (e) {
        ElMessage.error(String(e))
    } finally {
        cancellingTasks.value.delete(traceId)
    }
}

async function handleClear(traceId) {
    if (clearingTasks.value.has(traceId)) {
        return
    }
    clearingTasks.value.add(traceId)
    try {
        await clearAiWork(traceId)
        ElMessage.success('已清除任务')
        await loadAiStatus()
    } catch (e) {
        ElMessage.error(String(e))
    } finally {
        clearingTasks.value.delete(traceId)
    }
}

function taskDisplayName(task) {
  const convName = task.conv_display_name || ''
  const chatType = task.conv_chat_type || ''
  const senderName = task.conv_sender_name || ''
  if (chatType === 'group' && convName) {
    return senderName ? `${convName}:${senderName}` : convName
  }
  if (senderName) {
    return senderName
  }
  if (convName) {
    return convName
  }
  return task.chat_name || task.chat_id || '--'
}

function stageLabel(stage) {
  const map = {
    '接收消息': '接收消息',
    '等待 Agent 并发槽': '等待并发槽',
    '构建上下文并调用 Agent（流式）': 'Agent 推理中',
    '构建上下文并调用 Agent': 'Agent 推理中',
    '发送企微回复': '发送回复',
    '完成': '完成',
    '已截断': '已截断',
    '异常截断': '异常截断',
  }
  return map[stage] || stage
}

function statusType(status) {
  if (status === 'running') return 'primary'
  if (status === 'completed') return 'success'
  if (status === 'failed') return 'danger'
  if (status === 'cancelled' || status === 'cancel_requested') return 'warning'
  return 'info'
}

function formatTime(iso) {
  return formatTimeOnly(iso)
}

function reasoningPreview(task) {
  const reasoning = String(task?.reasoning || '').trim()
  if (reasoning) return reasoning
  const stage = stageLabel(task?.stage || '')
  if (isActiveStatus(task?.status)) {
    return stage ? `当前阶段：${stage}` : 'Agent 正在工作...'
  }
  return task?.error ? `异常：${task.error}` : '暂无思考链记录'
}

function closeAiStatusStream() {
  if (aiStatusController) {
    aiStatusController.abort()
    aiStatusController = null
  }
}

function scheduleReconnect() {
  if (streamStopped || reconnectTimer) {
    return
  }
  reconnectTimer = window.setTimeout(() => {
    reconnectTimer = null
    startAiStatusStream()
  }, 3000)
}

async function startAiStatusStream() {
  closeAiStatusStream()
  const controller = new AbortController()
  aiStatusController = controller
  try {
    const response = await fetchWithAuth('/api/ai/status/stream', {
      headers: { Accept: 'text/event-stream' },
      signal: controller.signal,
    })
    if (!response.ok || !response.body) {
      throw new Error(`AI status stream failed: ${response.status}`)
    }
    const reader = response.body.getReader()
    const decoder = new TextDecoder()
    let buffer = ''
    while (!controller.signal.aborted) {
      const { done, value } = await reader.read()
      if (done) break
      buffer += decoder.decode(value, { stream: true })
      let frameEnd = buffer.indexOf('\n\n')
      while (frameEnd !== -1) {
        const frame = buffer.slice(0, frameEnd)
        buffer = buffer.slice(frameEnd + 2)
        const dataLine = frame.split(/\r?\n/).find((line) => line.startsWith('data:'))
        if (dataLine) {
          try {
            aiStatus.value = JSON.parse(dataLine.slice(5).trim())
          } catch {
            // Ignore malformed frames and keep the last good payload.
          }
        }
        frameEnd = buffer.indexOf('\n\n')
      }
    }
  } catch {
    if (!controller.signal.aborted) {
      scheduleReconnect()
    }
  } finally {
    if (aiStatusController === controller) {
      aiStatusController = null
    }
  }
}

onMounted(() => {
  streamStopped = false
  loadAiStatus()
  startAiStatusStream()
})

onActivated(() => {
  loadAiStatus()
  streamStopped = false
  startAiStatusStream()
})

onDeactivated(() => {
  streamStopped = true
  closeAiStatusStream()
  if (reconnectTimer) {
    clearTimeout(reconnectTimer)
    reconnectTimer = null
  }
})

onBeforeUnmount(() => {
  streamStopped = true
  closeAiStatusStream()
  if (reconnectTimer) {
    clearTimeout(reconnectTimer)
    reconnectTimer = null
  }
})
</script>

<template>
  <section class="console-view">
    <div class="console-grid">
      <el-card class="panel console-panel" shadow="never">
        <template #header>
          <div class="panel-title split">
            <span>已启用 Bot</span>
          </div>
        </template>

        <div v-if="enabledBots.length" class="bot-card-grid">
          <article v-for="bot in enabledBots" :key="bot.bot_key" class="bot-service-card">
            <header class="bot-service-head">
              <div>
                <h3>{{ bot.name }}</h3>
                <p>{{ getAgentLabel(bot.agent_provider, agents) }}</p>
              </div>
              <el-tag :type="getStatus(bot.bot_key).running ? 'success' : 'info'" effect="dark" round>
                {{ getStatus(bot.bot_key).running ? '运行中' : '已停止' }}
              </el-tag>
            </header>

            <div class="metric-row metric-row--bot">
              <div>
                <span>MCP 数</span>
                <strong>{{ bot.enabled_mcp_count || 0 }}</strong>
              </div>
              <div>
                <span>Skills 数</span>
                <strong>{{ bot.enabled_skill_count || 0 }}</strong>
              </div>
              <div>
                <span>PID</span>
                <strong>{{ getStatus(bot.bot_key).pid || '-' }}</strong>
              </div>
            </div>

            <div class="prompt-preview">
              <span>提示词</span>
              <p :title="promptPreview(bot.system_prompt)">{{ promptPreview(bot.system_prompt) }}</p>
            </div>

            <footer class="actions bot-card-actions">
              <el-button
                type="success"
                :icon="VideoPlay"
                :disabled="getStatus(bot.bot_key).running || startingBots.has(bot.bot_key)"
                :loading="startingBots.has(bot.bot_key)"
                @click="emit('start-bot', bot.bot_key)"
              >
                启动服务
              </el-button>
              <el-button
                type="danger"
                :icon="VideoPause"
                :disabled="!getStatus(bot.bot_key).running || stoppingBots.has(bot.bot_key)"
                :loading="stoppingBots.has(bot.bot_key)"
                @click="emit('stop-bot', bot.bot_key)"
              >
                停止服务
              </el-button>
            </footer>
          </article>
        </div>

        <div v-else class="empty-block">
          <strong>暂无已启用 Bot</strong>
          <span>请先在 Bot 配置页面启用 Bot，再回到工作台查看运行状态。</span>
        </div>
      </el-card>

      <el-card class="panel console-panel" shadow="never">
        <template #header>
            <div class="panel-title split">
                <span>任务列表</span>
                <el-tag v-if="aiStatus.busy" type="warning" effect="dark" round size="small">运行中</el-tag>
            </div>
        </template>

        <div v-if="combinedTasks.length" class="task-list">
            <article v-for="task in combinedTasks" :key="task.trace_id" 
                     class="task-item" 
                     :class="{'task-item--active': isActiveStatus(task.status)}">
                <div class="task-item__head">
                    <strong>{{ taskDisplayName(task) }}</strong>
                    <el-tag :type="statusType(task.status)" round size="small">{{ stageLabel(task.stage) }}</el-tag>
                </div>
                <p class="task-item__question">{{ (task.question || '').slice(0, 100) }}</p>
                <pre class="task-item__answer">{{ reasoningPreview(task) }}</pre>
                <div class="task-item__meta">
                    <span>TraceId: {{ task.trace_id.slice(0, 8) }}...</span>
                    <span>{{ formatTime(task.started_at) }}</span>
                    <el-button v-if="isActiveStatus(task.status)" 
                               size="small" text type="danger" 
                               :loading="isCancelling(task.trace_id)" 
                               :disabled="isCancelling(task.trace_id)"
                               @click="handleCancel(task.trace_id)">
                        取消
                    </el-button>
                    <el-button v-else
                               size="small" text type="info" 
                               :loading="isClearing(task.trace_id)" 
                               :disabled="isClearing(task.trace_id)"
                               @click="handleClear(task.trace_id)">
                        清除
                    </el-button>
                </div>
            </article>
        </div>

        <div v-else class="empty-block empty-block--large">
            <strong>暂无任务</strong>
            <span>Bot 运行后，Agent 的调用任务会实时展示在这里。</span>
        </div>
      </el-card>
    </div>
  </section>
</template>
